# Site settings
#baseurl: "/kaiskauda/"
title: Kai Skauda
email: your-email@domain.com
description: > # Onkologinio skausmo pagalba
baseurl: "/kaiskauda/" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
  style: compressed